language: node_js
script: npm run-script test-travis
node_js:
- '0.10'
- '0.11'
after_script: npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: GG79c4r3MOI9a3VcuqzrWjvzdoa+0eo6CpLL16b9jYOX/dPa3HCzqYSgi4u/gvlzkBnGfDOu2hAozAy3uyAe/cMAik7brdOaD61ChhBY3JKG2w8yNbIuyqOaRhEF3OdVf3p/abXW+gUVb7b85OqqXgx21xJ8r5KEScF1oK29aDg=
  on:
    repo: wooorm/n-gram
